import React, { useState } from 'react';
import { patchDowryBudgets } from '../../api/buyerApi';
import {
  PieChart, Pie, Cell, Tooltip, Legend, ResponsiveContainer,
  BarChart, Bar, XAxis, YAxis, CartesianGrid,
} from 'recharts';
import { Sparkles, ArrowRight, TrendingUp, Info, HelpCircle, Save, CheckCircle2 } from 'lucide-react';

// 10-colour palette — repeats for more than 10 categories
const PALETTE = [
  '#a37b3d','#ECD4A8','#dfc08d','#d0ac72','#c09858',
  '#8a6633','#FDF2F3','#FBEFF1','#FEF4F7','#FFF5F8',
];

const formatPKR = (v) => {
  if (v >= 1000000) return `PKR ${(v / 1000000).toFixed(1)}M`;
  if (v >= 1000)    return `PKR ${(v / 1000).toFixed(0)}K`;
  return `PKR ${v}`;
};

const formatPKRFull = (v) =>
  new Intl.NumberFormat('en-PK', { style: 'currency', currency: 'PKR', maximumFractionDigits: 0 }).format(v);

function getSliderStep(amount) {
  if (amount > 1500000) return 500;
  if (amount > 1000000) return 1000;
  if (amount > 500000)  return 2000;
  return 5000;
}

function getDeviationColor(current, original) {
  if (!original || original === 0) return 'green';
  const pct = Math.abs((current - original) / original) * 100;
  if (pct <= 10) return 'green';
  if (pct <= 30) return 'yellow';
  return 'red';
}

const DEVIATION_STYLES = {
  green:  { bar: 'bg-green-500',  label: 'text-green-700',  badge: 'bg-green-50 text-green-700 border-green-200' },
  yellow: { bar: 'bg-yellow-500', label: 'text-yellow-700', badge: 'bg-yellow-50 text-yellow-700 border-yellow-200' },
  red:    { bar: 'bg-red-500',    label: 'text-red-700',    badge: 'bg-red-50 text-red-700 border-red-200' },
};

// ── helpers ───────────────────────────────────────────────────────────────────
function readDowry(buyerId) {
  try {
    if (buyerId) return JSON.parse(localStorage.getItem(`ss_dowry_${buyerId}`) || 'null');
    return JSON.parse(localStorage.getItem('ss_dowry_latest') || 'null');
  } catch { return null; }
}

function writeDowry(data, buyerId) {
  const s = JSON.stringify(data);
  localStorage.setItem('ss_dowry_latest', s);
  if (buyerId) localStorage.setItem(`ss_dowry_${buyerId}`, s);
}

// ── StepResults ───────────────────────────────────────────────────────────────
function StepResults({ result, loading, saved, adjustedEstimates, onAdjust, onSave, onReset, priorities, categories = [], buyerId }) {
  const catLabel = (key) => categories.find(c => c.category_id === key)?.label || key.replace(/_/g,' ');
  const catColor = (key) => {
    const idx = categories.findIndex(c => c.category_id === key);
    return PALETTE[(idx >= 0 ? idx : 0) % PALETTE.length];
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-16">
        <div className="w-12 h-12 border-4 border-primary-100 border-t-primary-500 rounded-full animate-spin mb-4" />
        <p className="text-sm font-medium text-gray-500">Running Hybrid Engine (Rule + Market Prices + ML)...</p>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="text-center py-16 text-gray-400">
        <p className="text-4xl mb-3">📊</p>
        <p>Complete the previous steps to see your estimation results.</p>
      </div>
    );
  }

  const displayBreakdown = {};
  for (const [key, val] of Object.entries(result.category_breakdown || {})) {
    displayBreakdown[key] = adjustedEstimates[key] !== undefined ? adjustedEstimates[key] : val;
  }

  const adjustedTotal = Object.values(displayBreakdown).reduce((a, b) => a + b, 0);

  const sortedEntries = Object.entries(displayBreakdown)
    .filter(([key, v]) => v > 0 && (priorities ? priorities[`priority_${key}`] !== 'Not_Wanted' : true))
    .sort(([, a], [, b]) => b - a);

  const pieData = sortedEntries.map(([key, value]) => ({
    name: catLabel(key), value, key, color: catColor(key),
  }));

  const barData = sortedEntries.map(([key, value]) => ({
    name: catLabel(key), amount: value, color: catColor(key),
  }));

  return (
    <div className="space-y-8 animate-fade-in">
      <div>
        <h2 className="text-2xl font-extrabold text-gray-950 tracking-tight mb-1">Results Dashboard</h2>
        <p className="text-sm text-gray-500 font-light">
          Your tailored estimate generated by our Hybrid Price Engine. Fine-tune limits below.
        </p>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="bg-gradient-to-br from-[#a37b3d] to-[#ECD4A8] rounded-2xl p-5 text-white shadow-md shadow-[#ECD4A8]/20">
          <p className="text-[10px] uppercase font-bold tracking-wider opacity-85">Total Budget</p>
          <p className="text-xl font-black mt-1.5">{formatPKRFull(adjustedTotal)}</p>
          {adjustedTotal !== result.total_recommended_budget && (
            <p className="text-[10px] opacity-75 mt-1">System: {formatPKR(result.total_recommended_budget)}</p>
          )}
        </div>
        <div className="bg-white rounded-2xl p-5 border border-primary-200 shadow-sm">
          <p className="text-[10px] uppercase font-bold text-gray-400 tracking-wider">From Income</p>
          <p className="text-xl font-bold text-gray-900 mt-1.5">{formatPKR(result.budget_sources?.from_income || 0)}</p>
          <p className="text-[10px] text-primary-900 font-bold mt-1 bg-primary-50 px-2 py-0.5 rounded-md inline-block">
            {result.budget_sources?.income_percentage || 0}% of budget
          </p>
        </div>
        <div className="bg-white rounded-2xl p-5 border border-primary-200 shadow-sm">
          <p className="text-[10px] uppercase font-bold text-gray-400 tracking-wider">From Savings</p>
          <p className="text-xl font-bold text-gray-900 mt-1.5">{formatPKR(result.budget_sources?.from_savings || 0)}</p>
          <p className="text-[10px] text-primary-900 font-bold mt-1 bg-primary-50 px-2 py-0.5 rounded-md inline-block">
            {result.budget_sources?.savings_percentage || 0}% of budget
          </p>
        </div>
        <div className="bg-white rounded-2xl p-5 border border-primary-200 shadow-sm">
          <p className="text-[10px] uppercase font-bold text-gray-400 tracking-wider">Safety Index</p>
          <p className="text-xl font-bold text-gray-900 mt-1.5">{(result.responsibility_score * 100).toFixed(0)}%</p>
          <p className="text-[10px] text-emerald-600 font-bold mt-1 bg-emerald-50 px-2 py-0.5 rounded-md inline-block">
            Calculated Risk Zone
          </p>
        </div>
      </div>

      {/* Sliders Panel */}
      <div className="border border-primary-200/60 rounded-3xl p-6 bg-white shadow-sm space-y-6">
        <div>
          <h3 className="text-base font-bold text-gray-900 flex items-center gap-1.5">
            <TrendingUp size={18} className="text-primary-900" /> Fine-Tune Category Allocations
          </h3>
          <p className="text-xs text-gray-400 mt-0.5 font-light">Drag individual sliders to rebalance funds. The total budget updates automatically.</p>
        </div>
        
        <div className="space-y-6">
          {Object.entries(result.category_breakdown || {}).map(([key, originalAmt]) => {
            const current   = displayBreakdown[key] ?? originalAmt;
            const step      = getSliderStep(originalAmt);
            const maxVal    = Math.max(originalAmt * 2, step * 20);
            const deviation = getDeviationColor(current, originalAmt);
            const styles    = DEVIATION_STYLES[deviation];
            const devPct    = originalAmt > 0
              ? (((current - originalAmt) / originalAmt) * 100).toFixed(0)
              : 0;
            const color = catColor(key);

            if (priorities && priorities[`priority_${key}`] === 'Not_Wanted') return null;
            if (!priorities && originalAmt === 0) return null;

            return (
              <div key={key} className="space-y-1.5 p-3 rounded-2xl bg-gray-50/40 border border-gray-100 hover:bg-gray-50/90 transition-colors duration-200">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: color }} />
                    <span className="text-xs font-bold text-gray-900 capitalize">{catLabel(key)}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className={`text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-md border ${styles.badge}`}>
                      {devPct > 0 ? `+${devPct}%` : devPct < 0 ? `${devPct}%` : 'Locked'}
                    </span>
                    <span className={`text-xs font-extrabold font-mono ${styles.label}`}>
                      {formatPKR(current)}
                    </span>
                  </div>
                </div>
                <input
                  type="range" min={0} max={maxVal} step={step} value={current}
                  onChange={(e) => onAdjust && onAdjust(key, Number(e.target.value))}
                  disabled={!onAdjust}
                  className={`w-full h-1.5 rounded-full appearance-none ${onAdjust ? 'cursor-pointer' : 'cursor-not-allowed opacity-60'}`}
                  style={{
                    background: `linear-gradient(to right, ${color} ${(current / maxVal) * 100}%, #e5e7eb ${(current / maxVal) * 100}%)`,
                  }}
                />
                <div className="flex justify-between text-[10px] text-gray-400 font-medium px-0.5">
                  <span>PKR 0</span>
                  <span>Sys Reference: {formatPKR(originalAmt)}</span>
                  <span>{formatPKR(maxVal)}</span>
                </div>
              </div>
            );
          })}
        </div>

        <div className="pt-5 border-t border-gray-100 flex items-center justify-between">
          <span className="text-xs font-bold text-gray-500 uppercase tracking-wider">Total Adjusted Budget</span>
          <span className="text-xl font-black text-primary-950">{formatPKRFull(adjustedTotal)}</span>
        </div>
      </div>

      {/* Visual Analytics */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="border border-primary-200 rounded-3xl p-6 bg-white shadow-sm">
          <h3 className="text-sm font-bold text-gray-950 mb-1">Budget Breakdown</h3>
          <p className="text-[10px] text-gray-400 font-semibold uppercase tracking-wider mb-4">Pie Representation</p>
          <ResponsiveContainer width="100%" height={260}>
            <PieChart>
              <Pie data={pieData} dataKey="value" nameKey="name"
                cx="50%" cy="50%" outerRadius={75} innerRadius={45} paddingAngle={3}
                label={({ percent }) => `${(percent * 100).toFixed(0)}%`}
              >
                {pieData.map((entry, i) => <Cell key={i} fill={entry.color} />)}
              </Pie>
              <Tooltip formatter={(v) => formatPKRFull(v)} />
              <Legend verticalAlign="bottom" height={36} wrapperStyle={{ fontSize: 10, fontWeight: 'bold' }} />
            </PieChart>
          </ResponsiveContainer>
        </div>

        <div className="border border-primary-200 rounded-3xl p-6 bg-white shadow-sm">
          <h3 className="text-sm font-bold text-gray-950 mb-1">Comparative Chart</h3>
          <p className="text-[10px] text-gray-400 font-semibold uppercase tracking-wider mb-4">Amounts comparison</p>
          <ResponsiveContainer width="100%" height={260}>
            <BarChart data={barData} layout="vertical" margin={{ left: -10, right: 10 }}>
              <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#f3f4f6" />
              <XAxis type="number" tickFormatter={formatPKR} tick={{ fontSize: 9 }} />
              <YAxis dataKey="name" type="category" width={80} tick={{ fontSize: 9, fontWeight: 'bold' }} />
              <Tooltip formatter={(v) => formatPKRFull(v)} />
              <Bar dataKey="amount" radius={[0, 4, 4, 0]}>
                {barData.map((entry, i) => <Cell key={i} fill={entry.color} />)}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Community Matches */}
      {result.training_matches?.length > 0 && (
        <CommunityInsights matches={result.training_matches} myBudget={adjustedTotal} />
      )}

      {/* Table breakdown */}
      <div className="border border-primary-200/50 rounded-3xl overflow-hidden bg-white shadow-sm">
        <table className="w-full text-xs">
          <thead>
            <tr className="bg-gray-50 border-b border-gray-100">
              <th className="text-left px-5 py-3.5 text-gray-500 font-bold uppercase tracking-wider">Category</th>
              <th className="text-right px-5 py-3.5 text-gray-500 font-bold uppercase tracking-wider">System Default</th>
              <th className="text-right px-5 py-3.5 text-gray-500 font-bold uppercase tracking-wider">Adjusted Value</th>
              <th className="text-right px-5 py-3.5 text-gray-500 font-bold uppercase tracking-wider">% allocation</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-50">
            {Object.entries(result.category_breakdown || {})
              .filter(([key]) => priorities ? priorities[`priority_${key}`] !== 'Not_Wanted' : true)
              .map(([key, sysAmt]) => {
                const adjusted = displayBreakdown[key] ?? sysAmt;
                const pct      = adjustedTotal > 0 ? ((adjusted / adjustedTotal) * 100).toFixed(1) : 0;
                const dev      = getDeviationColor(adjusted, sysAmt);
                const styles   = DEVIATION_STYLES[dev];
                return (
                  <tr key={key} className="hover:bg-primary-50/20 transition-colors">
                    <td className="px-5 py-3.5 flex items-center gap-2 font-bold text-gray-800 capitalize">
                      <div className="w-2.5 h-2.5 rounded-full shrink-0" style={{ backgroundColor: catColor(key) }} />
                      {catLabel(key)}
                    </td>
                    <td className="text-right px-5 py-3.5 font-mono text-gray-400 font-medium">{formatPKRFull(sysAmt)}</td>
                    <td className={`text-right px-5 py-3.5 font-mono font-extrabold ${styles.label}`}>{formatPKRFull(adjusted)}</td>
                    <td className="text-right px-5 py-3.5 text-gray-500 font-semibold">{pct}%</td>
                  </tr>
                );
              })}
          </tbody>
        </table>
      </div>

      {buyerId && (
        <BudgetManageSection buyerId={buyerId} categories={categories} />
      )}

      {/* Advisory Notes */}
      {result.notes?.length > 0 && (
        <div className="bg-primary-50/30 border border-primary-200 rounded-3xl p-5 relative overflow-hidden">
          <h3 className="text-xs font-bold text-primary-900 uppercase tracking-wider mb-3 flex items-center gap-1.5">
            <Info size={14} className="text-primary-800" /> Hybrid Engine Advice Notes
          </h3>
          <ul className="space-y-2">
            {result.notes.map((note, i) => (
              <li key={i} className="text-xs text-gray-600 leading-relaxed flex items-start gap-2.5 font-medium">
                <span className="text-primary-800 mt-0.5 shrink-0">•</span>{note}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

// ── Community Insights ────────────────────────────────────────────────────────
function incomeBucket(income) {
  if (income <  30000) return "< 30K";
  if (income <  50000) return "30K–50K";
  if (income <  75000) return "50K–75K";
  if (income < 100000) return "75K–100K";
  if (income < 150000) return "100K–150K";
  if (income < 200000) return "150K–200K";
  if (income < 300000) return "200K–300K";
  return "300K+";
}

function CommunityInsights({ matches, myBudget }) {
  return (
    <div className="border border-primary-200/60 rounded-3xl overflow-hidden bg-white shadow-sm">
      <div className="bg-primary-50/50 px-5 py-4 border-b border-primary-200/40">
        <h3 className="text-sm font-bold text-gray-900 flex items-center gap-1.5">
          <Sparkles size={16} className="text-primary-800" /> Community Insights
        </h3>
        <p className="text-xs text-gray-400 mt-0.5 font-light">
          Compare details with {matches.length} similar user profiles in our database.
        </p>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-xs">
          <thead>
            <tr className="bg-gray-50 border-b border-gray-100">
              <th className="text-left px-5 py-3 text-gray-500 font-bold uppercase tracking-wider">Income Range</th>
              <th className="text-center px-5 py-3 text-gray-500 font-bold uppercase tracking-wider">Family Details</th>
              <th className="text-right px-5 py-3 text-gray-500 font-bold uppercase tracking-wider">Recommended Budget</th>
              <th className="text-right px-5 py-3 text-gray-500 font-bold uppercase tracking-wider">Deviation vs Yours</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-50">
            {matches.map((m, i) => {
              const dev      = m.deviation_pct;
              const devColor = Math.abs(dev) <= 10 ? "text-emerald-600 bg-emerald-50 border-emerald-100" : Math.abs(dev) <= 25 ? "text-amber-600 bg-amber-50 border-amber-100" : "text-rose-600 bg-rose-50 border-rose-100";
              return (
                <tr key={i} className="hover:bg-primary-50/10 transition-colors">
                  <td className="px-5 py-3.5 text-gray-800 font-bold">PKR {incomeBucket(m.income)}/mo</td>
                  <td className="px-5 py-3.5 text-center text-gray-500 font-medium">{m.total_family_members} members</td>
                  <td className="px-5 py-3.5 text-right font-mono text-gray-800 font-extrabold">{formatPKRFull(m.total_recommended_budget)}</td>
                  <td className="px-5 py-3.5 text-right font-semibold">
                    <span className={`inline-block px-2.5 py-0.5 rounded-full border text-[10px] font-bold ${devColor}`}>
                      {dev > 0 ? `+${dev}%` : dev < 0 ? `${dev}%` : 'Same'}
                    </span>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ── Budget Manage Section ────────────────────────────────────────────────────
function BudgetManageSection({ buyerId, categories }) {
  const catLabel = (id) => categories.find(c => c.category_id === id)?.label || id.replace(/_/g, ' ');

  const [dowry, setDowry] = useState(() => readDowry(buyerId));
  const [fromCat, setFromCat] = useState('');
  const [toCat, setToCat]   = useState('');
  const [amount, setAmount] = useState('');
  const [msg, setMsg]       = useState({ text: '', error: false });

  const budgets = dowry?.category_budgets || {};
  // Only show categories that are active (not Not_Wanted) and have a budget
  const cats = Object.entries(budgets).filter(([, v]) => v.active !== false);

  const fromBudget = fromCat ? budgets[fromCat] : null;
  const maxShift   = fromBudget ? (fromBudget.remaining ?? fromBudget.estimated ?? 0) : 0;

  const handleShift = () => {
    const amt = Number(amount);
    if (!fromCat || !toCat) return setMsg({ text: 'Select both source and destination categories.', error: true });
    if (fromCat === toCat)  return setMsg({ text: 'Source and destination must be different.', error: true });
    if (!amt || amt <= 0)   return setMsg({ text: 'Enter a valid amount greater than 0.', error: true });
    if (amt > maxShift)     return setMsg({ text: `Max available from ${catLabel(fromCat)}: PKR ${maxShift.toLocaleString()}`, error: true });

    const b = { ...budgets };
    const srcEst  = b[fromCat].estimated || 0;
    const srcLeft = b[fromCat].remaining ?? srcEst;
    const dstEst  = b[toCat].estimated  || 0;
    const dstLeft = b[toCat].remaining  ?? dstEst;
    b[fromCat] = { ...b[fromCat], estimated: srcEst - amt, remaining: srcLeft - amt };
    b[toCat]   = { ...b[toCat],  estimated: dstEst + amt, remaining: dstLeft + amt };

    const updated = { ...dowry, category_budgets: b };
    writeDowry(updated, buyerId);
    setDowry(updated);
    // Persist to MongoDB and signal all other components
    patchDowryBudgets(buyerId, b).catch(() => {});
    window.dispatchEvent(new CustomEvent('dowry-updated', { detail: { buyerId } }));
    setMsg({ text: `✓ Shifted PKR ${amt.toLocaleString()} from ${catLabel(fromCat)} → ${catLabel(toCat)}.`, error: false });
    setAmount('');
  };

  if (!dowry || cats.length < 2) return null;

  return (
    <div className="border border-primary-200/60 rounded-3xl p-6 bg-white shadow-sm space-y-4">
      <div>
        <h3 className="text-sm font-bold text-gray-900">Reallocate Budget Between Categories</h3>
        <p className="text-xs text-gray-400 mt-0.5 font-light">Shift funds from one category to another to fine-tune your plan.</p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div>
          <label className="block text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1">From</label>
          <select
            value={fromCat}
            onChange={e => { setFromCat(e.target.value); setMsg({ text: '', error: false }); }}
            className="w-full border border-gray-200/80 bg-white rounded-2xl px-4 py-2.5 text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500 transition-all">
            <option value="">Select category…</option>
            {cats.filter(([k]) => k !== toCat).map(([k, v]) => (
              <option key={k} value={k}>
                {catLabel(k)} — PKR {(v.remaining ?? v.estimated ?? 0).toLocaleString()} left
              </option>
            ))}
          </select>
        </div>

        <div>
          <label className="block text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1">To</label>
          <select
            value={toCat}
            onChange={e => { setToCat(e.target.value); setMsg({ text: '', error: false }); }}
            className="w-full border border-gray-200/80 bg-white rounded-2xl px-4 py-2.5 text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500 transition-all">
            <option value="">Select category…</option>
            {cats.filter(([k]) => k !== fromCat).map(([k]) => (
              <option key={k} value={k}>{catLabel(k)}</option>
            ))}
          </select>
        </div>

        <div>
          <label className="block text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1">Amount (PKR)</label>
          <div className="flex gap-2">
            <input
              type="number" value={amount} min="1" max={maxShift || undefined}
              onChange={e => { setAmount(e.target.value); setMsg({ text: '', error: false }); }}
              placeholder="0"
              className="flex-1 border border-gray-200/80 rounded-2xl px-4 py-2.5 text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500 transition-all"
            />
            <button
              onClick={handleShift}
              className="px-5 py-2.5 bg-gradient-to-r from-[#a37b3d] to-[#ECD4A8] text-white rounded-2xl text-xs font-bold transition-all shadow-md shadow-[#ECD4A8]/20 hover:opacity-95 cursor-pointer">
              Shift →
            </button>
          </div>
        </div>
      </div>

      {fromCat && (
        <p className="text-[10px] text-gray-400 font-medium px-0.5">
          Available from <span className="font-bold text-primary-900">{catLabel(fromCat)}</span>: PKR {maxShift.toLocaleString()}
        </p>
      )}

      {msg.text && (
        <p className={`text-xs px-4 py-2.5 rounded-2xl font-semibold border ${msg.error ? 'bg-rose-50 border-rose-100 text-rose-800' : 'bg-emerald-50 border-emerald-100 text-emerald-800'}`}>
          {msg.text}
        </p>
      )}
    </div>
  );
}

export default StepResults;
